### ISSUE TITLE
Youtube removed export function

### ISSUE THREAD

**Issue by Fooftilly** [gavinlyonsrepo/opml_convert_RSS#1]
Youtube removed the export function for subscriptions. Is there any other way to export subscriptions?

**Comment by gavinlyonsrepo** [comment]
Hi 

It looks like as of 10/29/20, typing  youtube.com/subscription_manager  now takes you to youtube.com/feed/channels 
and the export button  is gone. 

No,  I don't know any other way at present to export subs , I will  have to look into it.

**Comment by gavinlyonsrepo** [comment]
Hi 

I have  found another method. 

There is a service in google called takeout at   https://takeout.google.com/
It lets you download your data. 

1. Select the youtube  account
2. Select only youtube data
3. select only youtube subs.
Then  you can download the data. 

Unfortunately it is in JSON instead of XML  format so I will have to change my code , I will do this now.

Regards.

**Comment by gavinlyonsrepo** [comment]
Hi

Released new , 1.3-3 version which can convert the JSON file provided by google takeout.

**Comment by Fooftilly** [comment]
Thanks!
